apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: secretsa
      containers:
      - name: nginx
        image: ubuntu:20.04
        command: ["/bin/sh" , "-c"]
        args: ["sleep 999999"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mysecretvol
          mountPath: /app/server.ini
          subPath: <NameOfSecret>
      volumes:
      - name: mysecretvol
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: <name of the object>