apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysecret
spec:
  provider: aws
  # objectType: "ssmparameter"
  parameters:
    objects: |
      - objectName: "$SECRET_NAME"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
  secretObjects:
    - secretName: k8ssecret
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
# if name contains -
# - path: '"hyphenated-path"'
#objectAlias: '"hyphenated-alias"

#   objects: |
#     - objectName: "$SECRET_NAME"
#       objectType: "secretsmanager"
#       jmesPath:
#         - path: username
#           objectAlias: username
#         - path: password
#           objectAlias: password
# secretObjects:
#   - secretName: catalog-secret
#     type: Opaque
#     data:
#       - objectName: username
#         key: username
#       - objectName: password
#         key: password