Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs where the EC2 instances will be launched
  ClusterName:
    Type: String
    Default: "mycluster"
  MinNodes:
    Type: Number
    Default: 2
  DesireNodes:
    Type: Number
    Default: 3
  MaxNodes:
    Type: Number
    Default: 5  

Resources:
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Ref ClusterName
      NodeRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/ArpEksEc2NodeGroupRole'
      ScalingConfig:
        MinSize: !Ref MinNodes
        DesiredSize: !Ref DesireNodes
        MaxSize: !Ref MaxNodes
      Labels:
        EksCluster : !Ref ClusterName
      Subnets: !Ref SubnetIds