MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: application/node.eks.aws

---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    apiServerEndpoint: https://B85DA3F2D49BFA2FFA1ED5715323FE0B.gr7.us-east-1.eks.amazonaws.com
    certificateAuthority: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVzR3Q0NmSVlGNmt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNE1UWXhOakV6TXpkYUZ3MHpOREE0TVRReE5qRTRNemRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURZa0VLc2pzMmJMOXRGbFByWExVc3Bibm9idmE2Q002TGltUVNEMGRVck5DcXRkWXdJYmd2OTh6WDIKclNFbVRhbmxVSzVsZk92TmdIUXZOZlVOVmRLZmtxU3BtOUd2aHBvZ3VGTlBZQjdVeEpTa1lKbG01WElKMldPWgp1T1BnM1ZhNDhOdE1FQ1hCa1gwWkgxZGhJcUlmU2JlUm1GR1NtZ0xuc3NTdVdnaWVvK2F2c2h0NDdPdzVick5XCktwdTl3SE9PSlRmOUhKZmZBNmp0UEZnUXltU0hkQzY1ek9TQzY5OWZCN0MwR204NEd0T1FrK2lpeXVqQnFsWVoKWVFEYVA3VHJkZVA1YWFNRmM0VkZCVm8xZTRjTmd3c0phcXZ5UjJZSjQvK0E4NExpVE1vMDZhUFhxQ0pLaUoxTgpla3dsZEQ5ci9RMGdvVUczbktpU0NpRHdOZ2lQQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWExCM0RNTEJUVTRyU1R1RWZXRHF5NjFqN3J6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlJvYnk0NkN5UApMZXpJOFJtOHU1VkNBcUl3L0NtSTFtZ3ZXTE5VSXVrSHFicS85MzQ3TE9uZDNQK0J0ZWZETUtmUE9PMkozUUMvCjZkK1BlOEdDSmpvUE9pazExWkVUS1d5cStSNmdhWDN4YVpBc250akszbTg0Z3lJM05aN3M4RHIyVDg4YUFSd3YKUFdxcTIybElyc3R1dGZ4bXpFVGVwbERQUHpLSVhEMmEvSTl3OFVNeWRnYUJuaE1EODBJaW9NU0xmQ0o3YW4yRgpiWUlMMzllZmFMTkQzZWN5L0J4OVJqQTRwTjJkb3ovTnRPOURzU2tzUEN3cHNsTFRmR203dGRBZkgyL3RJVDk0CkFkVEZvRHYzMm82ZWErQlFvbUxaVmhPRTkxVXQwTTRjTU9peFhtU3JiVUN2L1RWM0dKZVNuaFNlczZWWEkxd2MKemhBVmdSUTdVMHhoCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    cidr: 10.120.0.0/16
    name: mycluster
  kubelet:
    config:
      maxPods: 17
      clusterDNS:
      - 10.120.0.10
    flags:
    - "--node-labels=eks.amazonaws.com/nodegroup-image=ami-078a88e6816d5e04a,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=test"

--//--