apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
  # ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/opt/volume/nginx"

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: vol
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 3Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/opt/volume/nginx"
